{% set name = "Hypernets" %}
{% set version = "0.2.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/DataCanvasIO/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: ee412fde54c2315a89b0a4f118e663d57cd24c4db9d6956d7323b3720333997e

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - numpy >=1.16.5
    - pandas >=0.25.3
    - scikit-learn >=0.22.1,<1.0.0
    - scipy
    - lightgbm >=2.2.0
    - fsspec >=0.8.0
    - seaborn >=0.11.0
    - six
    - dask
    - distributed
    - dask-ml
    - pyarrow
    - ipython
    - traitlets
    - featuretools >=0.23.0,<1.0.0
    - python-geohash
    - pytest

test:
  imports:
    - hypernets
    - hypernets.examples
    - hypernets.tests
  requires:
    - pip
  commands:
    - pip check
    - python -m hypernets.examples.smoke_testing

about:
  home: https://github.com/DataCanvasIO/Hypernets
  license: Apache-2.0
  license_file: LICENSE
  summary: 'A General Automated Machine Learning framework.'
  description: |
    Hypernets is a general AutoML framework, based on which it can implement automatic
    optimization tools for various machine learning frameworks and libraries, including
    deep learning frameworks such as tensorflow, keras, pytorch, and machine learning
    libraries like sklearn, lightgbm, xgboost, etc.  We introduced an abstract search
    space representation, taking into account the requirements of hyperparameter
    optimization and neural architecture search(NAS), making Hypernets a general
    framework that can adapt to various automated machine learning needs.
  doc_url: https://hypernets.readthedocs.io/
  dev_url: https://github.com/DataCanvasIO/Hypernets

extra:
  recipe-maintainers:
    - lixfz
